'on':
  push:
    tags:
    - '*'
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
        cache: gradle
    - uses: gradle/actions/setup-gradle@v3
    - name: build
      env:
        VERSION: ${{ github.ref_name }}
      run: ./gradlew makePackages
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: build/generated/pkl/packages/*
    - name: Sleep for 5 seconds (to resolve new pkl version release)
      run: sleep 5s
      shell: bash
    - name: create docs
      env:
        VERSION_NUM: ${{ github.ref_name }}
      run: |
        # Extract version number without the leading 'v'
        export VERSION=$(echo "${VERSION_NUM}" | sed -E 's/^v(.*)/\1/')
        ./gradlew pkldoc
    - name: setup pages
      uses: actions/configure-pages@v4
    - name: upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/pkldoc/pkldoc
    - name: Upload files to Firebase Storage
      run: |
        # Install the Firebase CLI
        npm install -g firebase-tools

        # Upload all files in the kdeps/schema/deps directory
        firebase deploy --only storage:kdeps-schema/kdeps/schema/deps --token ${{ secrets.FIREBASE_TOKEN }}
    permissions:
      contents: write
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
    - id: deployment
      name: deploy pages
      uses: actions/deploy-pages@v4
    needs: build-and-upload
    permissions:
      pages: write
      id-token: write
    environment:
      name: pkl-docs
      url: ${{ steps.deployment.outputs.page_url }}
